.TH "portsmanrc" "5" "0.2" "Anselm R. Garbe" "System utilities"
.SH "NAME"
.LP 
portsmanrc \- portsman configuration file.

.SH "DESCRIPTION"
.LP 
You can configure portsman through using a \fI.portsmanrc\fR in your home directory. Portsman will determine automatically this file.
The \fIportsmanrc\fR file has following syntax:

.SH "SYNTAX"
.LP 
.TP 
\fB#\fR (comment)
All characters until end of line will be ignored.
.TP 
\fB<key> = <value>\fR
Each line contains at most one \fI<key>=<value>\fR statement. The whole configuration of portsman is a key\-value based configuration. Following \fBkeys\fR are currently supported by portsman (case sensitive):
.TP 
\fBuse.metacats\fR
defines, if TRUE, that portsman should use also meta categories, or not if FALSE (default: TRUE)
.TP 
\fBtitlebar.fcolor\fR
defines the foreground color of the titlebar, allowed are all color values
.TP 
\fBtitlebar.bcolor\fR
defines the background color of the titlebar, allowed are all color values
.TP 
\fBbrowser.fcolor\fR
defines the foreground color of the browser
.TP 
\fBbrowser.bcolor\fR
defines the background color of the browser
.TP 
\fBstatusbar.fcolor\fR
defines the foreground color of the statusbar
.TP 
\fBstatusbar.bcolor\fR
defines the background color of the statusbar
.TP 
\fBcmdbar.fcolor\fR
defines the foreground color of the commandbar
.TP 
\fBcmdbar.bcolor\fR
defines the background color of the commandbar
.TP 
\fBselector.fcolor\fR
defines the foreground color of the selector
.TP 
\fBselector.bcolor\fR
defines the background color of the selector
.TP 
\fBindexfile\fR
defines path to index file (default is /usr/ports/INDEX.portsman)
.TP 
\fBpkgdir\fR
defines path to the package db directory (default is /var/db/pkg)
.TP 
\fBportsdir\fR
defines path to the dir of the ports collection
.TP 
\fBmake.cmd\fR
defines the make command (whitspaces aren't allowed)(default: make)
.TP 
\fBmake.ta rget.inst\fR
defines install target of make cmd (default: install)
.TP 
\fBmake.ta rget.deinst\fR
defines deinstall target of make (default: deinstall)
.TP 
\fBmake.ta rget.update\fR
defines update target of make (default: reinstall)
.TP 
\fBmake.option.force\fR
defines if the force option should be enabled by default (default: FALSE)
.TP 
\fBmake.option.force.arg\fR
defines the argument string (default: \-k)
.TP 
\fBmake.option.pkg\fR          
defines if the package option should be enabled by
.TP 
\fBmake.option.pkg.arg\fR      
defines package target of make (default: package)
.TP 
\fBmake.option.clean\fR      
defines if the clean option should be enabled by default (default: TRUE)
.TP 
\fBmake.option.clean.arg\fR    
defines clean target of make (default: clean)
.TP 
\fBmake.option.nochksum\fR     
defines no checksum verification option (default: FALSE)
.TP 
\fBmake.option.nochksum.arg\fR
(see above)
.TP 
\fBmake.option.nodeps\fR
defines no depends option (default: FALSE)
.TP 
\fBmake.option.nodeps.arg\fR
(see above)
.TP 
\fBmake.option.forcepkgreg\fR
defines force pkg verification option (default: FALSE)
.TP 
\fBmake.option.forcepkgreg.arg\fR
(see above)
.TP 
\fBmake.option.nopkgreg\fR
defines force pkg verification option (default: FALSE)
.TP 
\fBmake.option.nopkgreg.arg\fR
(see above)
.LP 
Following \fBvalues\fR are currently supported:
.TP 
\fBBLACK\fR color value
.TP 
\fBRED\fR color value
.TP 
\fBGREEN\fR color value
.TP 
\fBYELLOW\fR color value
.TP 
\fBBLUE\fR color value
.TP 
\fBMAGENTA\fR color value
.TP 
\fBCYAN\fR color value
.TP 
\fBCYAN\fR color value
.TP 
\fBSTRING\fR
string without inner whitespaces
.TP 
\fBTRUE\fR
bool
.TP 
\fBFALSE\fR
bool


.SH "FILES"
.LP 
\fI$HOME/.portsmanrc\fP
.SH "AUTHORS"
.LP 
Anselm R. Garbe <anselmg@t\-online.de>
.SH "SEE ALSO"
.LP 
\fIportsman(1)\fR
